rules:
  - id: hardcoded-password
    pattern-either:
      - patterns:
          - pattern: $VAR = "..."
          - metavariable-regex:
              metavariable: $VAR
              regex: (?i).*(PASSWORD|PASSWD|SECRET|CREDENTIAL).*
      - patterns:
          - pattern: $VAR = '...'
          - metavariable-regex:
              metavariable: $VAR
              regex: (?i).*(PASSWORD|PASSWD|SECRET|CREDENTIAL).*
    message: "Hardcoded password detected in '$VAR'. Use environment variables or a secrets manager instead."
    languages: [python, javascript, typescript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-798: Use of Hard-coded Credentials"
      owasp: "A3:2017 - Sensitive Data Exposure"

  - id: hardcoded-api-token
    pattern-either:
      - patterns:
          - pattern: $VAR = "..."
          - metavariable-regex:
              metavariable: $VAR
              regex: (?i).*(API_TOKEN|API_KEY|AUTH_TOKEN|ACCESS_TOKEN|BEARER_TOKEN|SECRET_KEY|PRIVATE_KEY).*
      - patterns:
          - pattern: $VAR = '...'
          - metavariable-regex:
              metavariable: $VAR
              regex: (?i).*(API_TOKEN|API_KEY|AUTH_TOKEN|ACCESS_TOKEN|BEARER_TOKEN|SECRET_KEY|PRIVATE_KEY).*
    message: "Hardcoded API token/key detected in '$VAR'. Use environment variables or a secrets manager instead."
    languages: [python, javascript, typescript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-798: Use of Hard-coded Credentials"
      owasp: "A3:2017 - Sensitive Data Exposure"
